name: 1. CI - Check PR (TG Bot)
on:
  push:
    branches: ["develop"]
    paths:
      - 'BackendSpring/**'

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: maven

      - name: Run Tests and Build
        working-directory: ./BackendSpring
        run: mvn clean verify
